spring:
  application:
    name: spring-boot-provider
server:
  port: 8082
  name: ${spring.application.name}
dubbo:
  application:
    id: ${spring.application.name}-${server.port}
    name: ${spring.application.name}-${server.port}
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.sdk.core.service.impl
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    status: server

